openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/683343/movie-seriesAPI/1.0.0
info:
  version: "1.0.0"
  title: Movie and Series API
  description: This is a simple Movie and Series API server
tags:
  - name: series
    description: Series API
  - name: movies
    description: Movies API
paths:
  /movies:
    get:
      tags:
        - movies
      description: returns all the movies
      operationId: getMovies
      parameters:
        - in: query
          name: page
          description: page number
          schema:
            type: integer
            format: int32
        - in: query
          name: title
          description: title of the movie
          schema:
            type: string
      responses:
        "200":
          description: List of movies with pagination
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieResponseList"
              example:
                - id: 1
                  title: "Pride and Prejudice"
                  overview: "A story of love and life among the landed English gentry during the Georgian era. Mr. Bennet is a gentleman living in Hertfordshire with his overbearing wife and five daughters, but if he dies their house will be inherited by a distant cousin whom they have never met, so the family's future happiness and security is dependent on the daughters making good marriages."
                  release_date: "2005-09-16"
                - id: 2
                  title: "God Father"
                  overview: "A combination of God Of Gamblers and The Sting. Git is a young mechanic working for his uncle in a small garage. Git's cousin is tricked out of a large amount of money by a card sharp, and Git promises revenge. But the card sharp, called \"Card Devil\", works for the ruthless gang boss Kwok, and Git is also tricked. Having pledged the garage against the debt, Git desperately seeks the assistance of the one man who is up to the task of tricking the crooks, Ghost Eye."
                  release_date: "1980-01-23"
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /movies/{id}:
    get:
      tags:
        - movies
      description: returns a movie by id
      operationId: getMovieById
      parameters:
        - in: path
          name: id
          description: id of the movie
          schema:
            type: integer
            format: int32
          required: true
      responses:
        "200":
          description: Movie object with details and trailer link
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieResponse"
              example:
                id: 1
                original_language: "en"
                original_title: "Pride and Prejudice"
                overview: "A story of love and life among the landed English gentry during the Georgian era. Mr. Bennet is a gentleman living in Hertfordshire with his overbearing wife and five daughters, but if he dies their house will be inherited by a distant cousin whom they have never met, so the family's future happiness and security is dependent on the daughters making good marriages."
                popularity: 87.654
                release_date: "2005-09-16"
                title: "Pride and Prejudice"
                trailerUrl: "https://www.youtube.com/watch?v=nHS-YjoxYGk"
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /tv-eries:
    get:
      tags:
        - series
      description: returns all the series
      operationId: getSeries
      parameters:
        - in: query
          name: page
          description: page number
          schema:
            type: integer
            format: int32
        - in: query
          name: title
          description: title of the series
          schema:
            type: string
      responses:
        "200":
          description: List of series with pagination
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SeriesResponseList"
              example:
                - id: 1
                  name: "The Simpsons"
                  overview: "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made a name for itself in its fearless satirical take on politics, media and American life in general."
                - id: 2
                  name: "Friends"
                  overview : "Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life."
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /tv-series/{id}:
    get:
      tags:
        - series
      description: returns a series by id
      operationId: getSeriesById
      parameters:
        - in: path
          name: id
          description: id of the series
          schema:
            type: integer
            format: int32
          required: true
      responses:
        "200":
          description: Series object with details and trailer link
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SeriesResponse"
              example:
                id: 1
                name: "The Simpsons"
                overview: "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made a name for itself in its fearless satirical take on politics, media and American life in general."
                originCountryArray:
                  - US
                originalLanguage: en
                originalName: "The Simpsons"
                trailerUrl: "https://www.youtube.com/watch?v=1QO5VZ2HJZo"
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
components:
  schemas:
    MovieResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        original_language:
          type: string
          nullable: true
        original_title:
          type: string
        overview:
          type: string
        popularity:
          type: number
          format: float
          nullable: true
        release_date:
          type: string
          format: date
        title:
          type: string
        trailerUrl:
          type: string
          nullable: true
    SeriesResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        overview:
          type: string
          nullable: true
        originCountryArray:
          type: array
          items:
            type: string
          nullable: true
        originalLanguage:
          type: string
          nullable: true
        originalName:
          type: string
          nullable: true
        trailerUrl:
          type: string
          nullable: true
    MovieResponseList:
      type: array
      items:
        $ref: "#/components/schemas/MovieResponse"
    SeriesResponseList:
      type: array
      items:
        $ref: "#/components/schemas/SeriesResponse"